version: 2

jobs:
  build_docker_image:
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin
      - run: docker pull appliedblockchain/k0-base || true
      - run: docker build -t appliedblockchain/k0-base .

  build_and_push_docker_image:
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin
      - run: docker pull appliedblockchain/k0-base || true
      - run: docker build -t appliedblockchain/k0-base .
      - run: docker tag appliedblockchain/k0-base appliedblockchain/k0-base:$CIRCLE_TAG
      - run: docker push appliedblockchain/k0-base:$CIRCLE_TAG
      - run: docker push appliedblockchain/k0-base

workflows:
  version: 2
  standard:
    jobs:
      - build_docker_image:
          context: org-global
          filters:
            tags:
              ignore: /^v\d+\.\d+.\d+$/
  versioned:
    jobs:
      - build_and_push_docker_image:
          context: org-global
          filters:
            tags:
              only: /^v\d+\.\d+.\d+$/
            branches:
              ignore: /.*/
